#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
#ifndef SERENDIPITYLO_SWIFT_H
#define SERENDIPITYLO_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import Foundation;
@import UIKit;
@import WebKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SerendipityLO",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("AccountCacheMO")
@interface AccountCacheMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class NSString;
@class NSDate;

@interface AccountCacheMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable accountAction;
@property (nonatomic, copy) NSString * _Nullable accountType;
@property (nonatomic) int32_t age;
@property (nonatomic, copy) NSDate * _Nullable dob;
@property (nonatomic, copy) NSString * _Nullable dobStringValue;
@property (nonatomic, copy) NSString * _Nullable gender;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable meta;
@property (nonatomic, copy) NSString * _Nullable postcode;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic, copy) NSString * _Nullable timezoneId;
@property (nonatomic, copy) NSString * _Nullable zipcode;
@end


SWIFT_CLASS_NAMED("ActivityEventMO")
@interface ActivityEventMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface ActivityEventMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable activityType;
@property (nonatomic) int32_t confidence;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timezoneId;
@end


SWIFT_CLASS_NAMED("AppStateMO")
@interface AppStateMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface AppStateMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable appStateEvent;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timeZoneId;
@end


SWIFT_CLASS_NAMED("BaseWindowMO")
@interface BaseWindowMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface BaseWindowMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) double start;
@property (nonatomic) double end;
@end


SWIFT_CLASS_NAMED("BatteryDataMO")
@interface BatteryDataMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface BatteryDataMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) int32_t level;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timeZoneId;
@end


SWIFT_CLASS_NAMED("CalendarActionMO")
@interface CalendarActionMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class NotificationActionMO;

@interface CalendarActionMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSDate * _Nullable absolute;
@property (nonatomic, strong) NotificationActionMO * _Nullable notificationAction;
@end


SWIFT_CLASS_NAMED("CloudMessagingTokenMO")
@interface CloudMessagingTokenMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface CloudMessagingTokenMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable token;
@property (nonatomic) BOOL hasUpdated;
@end


SWIFT_CLASS_NAMED("CodableGeofenceMO")
@interface CodableGeofenceMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface CodableGeofenceMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) double lng;
@property (nonatomic) double lat;
@property (nonatomic) double radius;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic) BOOL notifyOnEntry;
@property (nonatomic) BOOL notifyOnExit;
@property (nonatomic) BOOL isActive;
@end


SWIFT_CLASS_NAMED("ConnectionEventMO")
@interface ConnectionEventMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface ConnectionEventMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic, copy) NSString * _Nullable source;
@property (nonatomic, copy) NSString * _Nullable direction;
@property (nonatomic, copy) NSString * _Nullable portName;
@end


SWIFT_CLASS_NAMED("CoreAlgoMO")
@interface CoreAlgoMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface CoreAlgoMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) int32_t count;
@property (nonatomic, copy) NSDate * _Nullable day;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timeZoneId;
@property (nonatomic, copy) NSString * _Nullable type;
@end


SWIFT_CLASS_NAMED("CovaticLogMO")
@interface CovaticLogMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface CovaticLogMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable log;
@property (nonatomic) int32_t logType;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timeZoneId;
@end

@class WKWebView;
@class WKNavigation;
@class WKWebViewConfiguration;
@class WKNavigationAction;
@class WKWindowFeatures;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC13SerendipityLO24CovaticWebViewController")
@interface CovaticWebViewController : UIViewController <WKNavigationDelegate, WKUIDelegate>
- (void)viewDidLoad;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("DemographicPredictedMO")
@interface DemographicPredictedMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface DemographicPredictedMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable ageRange;
@property (nonatomic, copy) NSString * _Nullable gender;
@property (nonatomic) int32_t resolutionMode;
@property (nonatomic) int32_t type;
@property (nonatomic, copy) NSString * _Nullable iabAgeRange;
@end


SWIFT_CLASS_NAMED("FwOpsMO")
@interface FwOpsMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface FwOpsMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable apiName;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int32_t statusCode;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timeZoneId;
@end


SWIFT_CLASS_NAMED("GenderDataMO")
@interface GenderDataMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface GenderDataMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable gender;
@property (nonatomic) BOOL hasProcessed;
@property (nonatomic, copy) NSDate * _Nullable dateDataRequested;
@property (nonatomic, copy) NSString * _Nullable tokenisedName;
@end


SWIFT_CLASS_NAMED("GeoPointsMO")
@interface GeoPointsMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class POIMO;

@interface GeoPointsMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable geoHash;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable mode;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable poiId;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) POIMO * _Nullable pois;
@end


SWIFT_CLASS_NAMED("GeoTileMO")
@interface GeoTileMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface GeoTileMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable geoTileID;
@end


SWIFT_CLASS_NAMED("JourneyActionMO")
@interface JourneyActionMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface JourneyActionMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable setId;
@property (nonatomic, copy) NSString * _Nullable direction;
@property (nonatomic, strong) NotificationActionMO * _Nullable notificationAction;
@end


SWIFT_CLASS_NAMED("LocationMO")
@interface LocationMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface LocationMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) double distanceAdjustered;
@property (nonatomic) double distanceDelta;
@property (nonatomic) double horizontalAccuracy;
@property (nonatomic) BOOL isPrecise;
@property (nonatomic) BOOL isStationaryLocation;
@property (nonatomic, copy) NSString * _Nullable latitude;
@property (nonatomic, copy) NSString * _Nullable longtitude;
@property (nonatomic) double speed;
@property (nonatomic) BOOL strategyStateChange;
@property (nonatomic) BOOL switchToMoving;
@property (nonatomic) BOOL switchToStationary;
@property (nonatomic, copy) NSString * _Nullable tileId;
@property (nonatomic) double timeDelta;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timeZoneId;
@property (nonatomic) int32_t triggerType;
@end


SWIFT_CLASS_NAMED("MediaConsumptionMO")
@interface MediaConsumptionMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface MediaConsumptionMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSArray<NSString *> * _Nullable clusterTags;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable frameworkTags;
@property (nonatomic, copy) NSString * _Nullable mediaAction;
@property (nonatomic) double mediaAssetDuration;
@property (nonatomic, copy) NSString * _Nullable mediaAssetIdentifier;
@property (nonatomic, copy) NSString * _Nullable mediaAssetTitle;
@property (nonatomic, copy) NSString * _Nullable mediaDelivery;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable metaData;
@property (nonatomic) double playHeadPosition;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable tags;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic, copy) NSString * _Nullable timezoneId;
@property (nonatomic, copy) NSString * _Nullable geotile;
@end


SWIFT_CLASS_NAMED("MultiClusterMO")
@interface MultiClusterMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class PointLocationMO;
@class NSSet;

@interface MultiClusterMO (SWIFT_EXTENSION(SerendipityLO))
- (void)addPointsObject:(PointLocationMO * _Nonnull)value;
- (void)removePointsObject:(PointLocationMO * _Nonnull)value;
- (void)addPoints:(NSSet * _Nonnull)values;
- (void)removePoints:(NSSet * _Nonnull)values;
@end


@interface MultiClusterMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) double clusterRadius;
@property (nonatomic, copy) NSString * _Nullable clusterType;
@property (nonatomic) BOOL hasResidenceTag;
@property (nonatomic) BOOL hasSemanticTag;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) BOOL ishighFideltyVisitedPlace;
@property (nonatomic) BOOL isHomeResidence;
@property (nonatomic) BOOL isMainCluster;
@property (nonatomic) BOOL isResidence;
@property (nonatomic) BOOL isWorkCluster;
@property (nonatomic, copy) NSString * _Nullable postalCode;
@property (nonatomic, copy) NSArray<NSDate *> * _Nullable residenceOnDates;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable semanticTags;
@property (nonatomic) double stDev;
@property (nonatomic, copy) NSString * _Nullable tileId;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable seiCodes;
@property (nonatomic, copy) NSString * _Nullable livesIn;
@property (nonatomic, strong) PointLocationMO * _Nullable centerPoint;
@property (nonatomic, strong) PointLocationMO * _Nullable outerPoint;
@property (nonatomic, strong) NSSet * _Nullable points;
@end


SWIFT_CLASS_NAMED("NoiseClusterMO")
@interface NoiseClusterMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface NoiseClusterMO (SWIFT_EXTENSION(SerendipityLO))
- (void)addNoisePointsObject:(PointLocationMO * _Nonnull)value;
- (void)removeNoisePointsObject:(PointLocationMO * _Nonnull)value;
- (void)addNoisePoints:(NSSet * _Nonnull)values;
- (void)removeNoisePoints:(NSSet * _Nonnull)values;
@end


@interface NoiseClusterMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable clusterType;
@property (nonatomic, strong) NSSet * _Nullable noisePoints;
@end


SWIFT_CLASS_NAMED("NotificationActionMO")
@interface NotificationActionMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class NotificationPayloadMO;
@class WoosActionMO;
@class ProfileActionMO;

@interface NotificationActionMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, strong) NotificationPayloadMO * _Nullable payload;
@property (nonatomic, strong) WoosActionMO * _Nullable wooAction;
@property (nonatomic, strong) CalendarActionMO * _Nullable calendarAction;
@property (nonatomic, strong) JourneyActionMO * _Nullable journeyAction;
@property (nonatomic, strong) ProfileActionMO * _Nullable profileAction;
@end


SWIFT_CLASS_NAMED("NotificationPayloadMO")
@interface NotificationPayloadMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface NotificationPayloadMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable resourceUrl;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable urlLink;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable promotion;
@property (nonatomic, strong) NotificationActionMO * _Nullable notificationAction;
@end


SWIFT_CLASS_NAMED("POIMO")
@interface POIMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface POIMO (SWIFT_EXTENSION(SerendipityLO))
- (void)addGeoPointsObject:(GeoPointsMO * _Nonnull)value;
- (void)removeGeoPointsObject:(GeoPointsMO * _Nonnull)value;
- (void)addGeoPoints:(NSSet * _Nonnull)values;
- (void)removeGeoPoints:(NSSet * _Nonnull)values;
@end


@interface POIMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable geoTileId;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timeZoneId;
@property (nonatomic, strong) NSSet * _Nullable geoPoints;
@end


SWIFT_CLASS_NAMED("PointLocationMO")
@interface PointLocationMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class XYCoordMO;

@interface PointLocationMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) double accuracy;
@property (nonatomic) int64_t count;
@property (nonatomic) double lat;
@property (nonatomic) double lng;
@property (nonatomic, copy) NSString * _Nullable mClusterReference;
@property (nonatomic, copy) NSString * _Nullable protoPointStatus;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable vanillaPointStatus;
@property (nonatomic, strong) MultiClusterMO * _Nullable centerPoint;
@property (nonatomic, strong) NoiseClusterMO * _Nullable noisePoints;
@property (nonatomic, strong) MultiClusterMO * _Nullable outerPoint;
@property (nonatomic, strong) MultiClusterMO * _Nullable points;
@property (nonatomic, strong) XYCoordMO * _Nullable xyPosition;
@end


SWIFT_CLASS_NAMED("ProfileActionMO")
@interface ProfileActionMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface ProfileActionMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable actionId;
@property (nonatomic, copy) NSString * _Nullable cvcqlVersion;
@property (nonatomic, copy) NSDate * _Nullable expires;
@property (nonatomic) int32_t minVersion;
@property (nonatomic, copy) NSString * _Nullable profileName;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic, strong) NotificationActionMO * _Nullable notificationAction;
@end


SWIFT_CLASS_NAMED("ProfileAudienceSegmentMO")
@interface ProfileAudienceSegmentMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface ProfileAudienceSegmentMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable profileName;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable query;
@property (nonatomic) BOOL isExternal;
@property (nonatomic) int32_t version;
@property (nonatomic, copy) NSString * _Nullable cvcqlVersion;
@property (nonatomic) int32_t updateEvery;
@property (nonatomic) int32_t identificationState;
@property (nonatomic, copy) NSString * _Nullable profileId;
@property (nonatomic, copy) NSDate * _Nullable expiryDate;
@property (nonatomic, copy) NSDate * _Nullable lastEvaluatedTime;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable annotations;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable annotationsPOIDependencies;
@end


SWIFT_CLASS_NAMED("ProfileErrorsMO")
@interface ProfileErrorsMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface ProfileErrorsMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable actionId;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic) int32_t errorCode;
@end


SWIFT_CLASS_NAMED("RangeActionMO")
@interface RangeActionMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface RangeActionMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) int32_t start;
@property (nonatomic) int32_t end;
@property (nonatomic, strong) WoosActionMO * _Nullable wooAction;
@end


SWIFT_CLASS_NAMED("RequestManagerMO")
@interface RequestManagerMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface RequestManagerMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable additionalInfo;
@property (nonatomic, copy) NSDate * _Nullable completeTime;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSDate * _Nullable previousLastSent;
@property (nonatomic, copy) NSDate * _Nullable requestInitalisedTime;
@property (nonatomic) BOOL success;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timeZoneId;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable urlEndpoint;
@end


SWIFT_CLASS_NAMED("SeiCodeMO")
@interface SeiCodeMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface SeiCodeMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) int32_t acorncode;
@property (nonatomic, copy) NSString * _Nullable postcode;
@property (nonatomic, copy) NSString * _Nullable tileId;
@property (nonatomic, copy) NSString * _Nullable nuts3;
@end


SWIFT_CLASS_NAMED("SemanticPOISMO")
@interface SemanticPOISMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface SemanticPOISMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) double lat;
@property (nonatomic) double lng;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable setId;
@property (nonatomic, copy) NSString * _Nullable tileId;
@property (nonatomic, copy) NSString * _Nullable pointId;
@end


SWIFT_CLASS_NAMED("SetIDStoreMO")
@interface SetIDStoreMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface SetIDStoreMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSArray<NSString *> * _Nullable clusterTypes;
@property (nonatomic) BOOL hasData;
@property (nonatomic) BOOL isStaleData;
@property (nonatomic, copy) NSDate * _Nullable lastRequestRecievedTimestamp;
@property (nonatomic, copy) NSString * _Nullable setName;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable tileIds;
@property (nonatomic) BOOL periodicPassBySet;
@end


SWIFT_CLASS_NAMED("SmartNotificationMO")
@interface SmartNotificationMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface SmartNotificationMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) BOOL clicked;
@property (nonatomic) BOOL created;
@property (nonatomic) BOOL displayed;
@property (nonatomic, copy) NSString * _Nullable errorDescription;
@property (nonatomic) int32_t errorType;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSDate * _Nullable receivedDate;
@property (nonatomic) BOOL resolved;
@property (nonatomic, copy) NSDate * _Nullable resolvedDate;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic) BOOL foreground;
@end


SWIFT_CLASS_NAMED("StateEventMO")
@interface StateEventMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface StateEventMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
@property (nonatomic) BOOL state;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic) BOOL shouldSend;
@end


SWIFT_CLASS_NAMED("StreamingHearbeatMO")
@interface StreamingHearbeatMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface StreamingHearbeatMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) BOOL isConcluded;
@property (nonatomic, copy) NSString * _Nullable mediaId;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic, copy) NSString * _Nullable mediaAssetTitle;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
@property (nonatomic) double mediaAssetDuration;
@property (nonatomic, copy) NSString * _Nullable mediaDelivery;
@property (nonatomic, copy) NSString * _Nullable timezoneId;
@end




SWIFT_CLASS_NAMED("WoosActionMO")
@interface WoosActionMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface WoosActionMO (SWIFT_EXTENSION(SerendipityLO))
- (void)addRangeActionObject:(RangeActionMO * _Nonnull)value;
- (void)removeRangeActionObject:(RangeActionMO * _Nonnull)value;
- (void)addRangeAction:(NSSet * _Nonnull)values;
- (void)removeRangeAction:(NSSet * _Nonnull)values;
@end


@interface WoosActionMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) int32_t index;
@property (nonatomic) int32_t offset;
@property (nonatomic, copy) NSString * _Nullable wooCommenceFrom;
@property (nonatomic, copy) NSDate * _Nullable displayDate;
@property (nonatomic, strong) NSSet * _Nullable rangeAction;
@property (nonatomic, strong) NotificationActionMO * _Nullable notificationAction;
@end


SWIFT_CLASS_NAMED("XYCoordMO")
@interface XYCoordMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface XYCoordMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) double x;
@property (nonatomic) double y;
@property (nonatomic, strong) PointLocationMO * _Nullable pointLocation;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
#ifndef SERENDIPITYLO_SWIFT_H
#define SERENDIPITYLO_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import Foundation;
@import UIKit;
@import WebKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SerendipityLO",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("AccountCacheMO")
@interface AccountCacheMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class NSString;
@class NSDate;

@interface AccountCacheMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable accountAction;
@property (nonatomic, copy) NSString * _Nullable accountType;
@property (nonatomic) int32_t age;
@property (nonatomic, copy) NSDate * _Nullable dob;
@property (nonatomic, copy) NSString * _Nullable dobStringValue;
@property (nonatomic, copy) NSString * _Nullable gender;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable meta;
@property (nonatomic, copy) NSString * _Nullable postcode;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic, copy) NSString * _Nullable timezoneId;
@property (nonatomic, copy) NSString * _Nullable zipcode;
@end


SWIFT_CLASS_NAMED("ActivityEventMO")
@interface ActivityEventMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface ActivityEventMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable activityType;
@property (nonatomic) int32_t confidence;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timezoneId;
@end


SWIFT_CLASS_NAMED("AppStateMO")
@interface AppStateMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface AppStateMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable appStateEvent;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timeZoneId;
@end


SWIFT_CLASS_NAMED("BaseWindowMO")
@interface BaseWindowMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface BaseWindowMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) double start;
@property (nonatomic) double end;
@end


SWIFT_CLASS_NAMED("BatteryDataMO")
@interface BatteryDataMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface BatteryDataMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) int32_t level;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timeZoneId;
@end


SWIFT_CLASS_NAMED("CalendarActionMO")
@interface CalendarActionMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class NotificationActionMO;

@interface CalendarActionMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSDate * _Nullable absolute;
@property (nonatomic, strong) NotificationActionMO * _Nullable notificationAction;
@end


SWIFT_CLASS_NAMED("CloudMessagingTokenMO")
@interface CloudMessagingTokenMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface CloudMessagingTokenMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable token;
@property (nonatomic) BOOL hasUpdated;
@end


SWIFT_CLASS_NAMED("CodableGeofenceMO")
@interface CodableGeofenceMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface CodableGeofenceMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) double lng;
@property (nonatomic) double lat;
@property (nonatomic) double radius;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic) BOOL notifyOnEntry;
@property (nonatomic) BOOL notifyOnExit;
@property (nonatomic) BOOL isActive;
@end


SWIFT_CLASS_NAMED("ConnectionEventMO")
@interface ConnectionEventMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface ConnectionEventMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic, copy) NSString * _Nullable source;
@property (nonatomic, copy) NSString * _Nullable direction;
@property (nonatomic, copy) NSString * _Nullable portName;
@end


SWIFT_CLASS_NAMED("CoreAlgoMO")
@interface CoreAlgoMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface CoreAlgoMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) int32_t count;
@property (nonatomic, copy) NSDate * _Nullable day;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timeZoneId;
@property (nonatomic, copy) NSString * _Nullable type;
@end


SWIFT_CLASS_NAMED("CovaticLogMO")
@interface CovaticLogMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface CovaticLogMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable log;
@property (nonatomic) int32_t logType;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timeZoneId;
@end

@class WKWebView;
@class WKNavigation;
@class WKWebViewConfiguration;
@class WKNavigationAction;
@class WKWindowFeatures;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC13SerendipityLO24CovaticWebViewController")
@interface CovaticWebViewController : UIViewController <WKNavigationDelegate, WKUIDelegate>
- (void)viewDidLoad;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("DemographicPredictedMO")
@interface DemographicPredictedMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface DemographicPredictedMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable ageRange;
@property (nonatomic, copy) NSString * _Nullable gender;
@property (nonatomic) int32_t resolutionMode;
@property (nonatomic) int32_t type;
@property (nonatomic, copy) NSString * _Nullable iabAgeRange;
@end


SWIFT_CLASS_NAMED("FwOpsMO")
@interface FwOpsMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface FwOpsMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable apiName;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int32_t statusCode;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timeZoneId;
@end


SWIFT_CLASS_NAMED("GenderDataMO")
@interface GenderDataMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface GenderDataMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable gender;
@property (nonatomic) BOOL hasProcessed;
@property (nonatomic, copy) NSDate * _Nullable dateDataRequested;
@property (nonatomic, copy) NSString * _Nullable tokenisedName;
@end


SWIFT_CLASS_NAMED("GeoPointsMO")
@interface GeoPointsMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class POIMO;

@interface GeoPointsMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable geoHash;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable mode;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable poiId;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) POIMO * _Nullable pois;
@end


SWIFT_CLASS_NAMED("GeoTileMO")
@interface GeoTileMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface GeoTileMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable geoTileID;
@end


SWIFT_CLASS_NAMED("JourneyActionMO")
@interface JourneyActionMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface JourneyActionMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable setId;
@property (nonatomic, copy) NSString * _Nullable direction;
@property (nonatomic, strong) NotificationActionMO * _Nullable notificationAction;
@end


SWIFT_CLASS_NAMED("LocationMO")
@interface LocationMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface LocationMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) double distanceAdjustered;
@property (nonatomic) double distanceDelta;
@property (nonatomic) double horizontalAccuracy;
@property (nonatomic) BOOL isPrecise;
@property (nonatomic) BOOL isStationaryLocation;
@property (nonatomic, copy) NSString * _Nullable latitude;
@property (nonatomic, copy) NSString * _Nullable longtitude;
@property (nonatomic) double speed;
@property (nonatomic) BOOL strategyStateChange;
@property (nonatomic) BOOL switchToMoving;
@property (nonatomic) BOOL switchToStationary;
@property (nonatomic, copy) NSString * _Nullable tileId;
@property (nonatomic) double timeDelta;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timeZoneId;
@property (nonatomic) int32_t triggerType;
@end


SWIFT_CLASS_NAMED("MediaConsumptionMO")
@interface MediaConsumptionMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface MediaConsumptionMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSArray<NSString *> * _Nullable clusterTags;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable frameworkTags;
@property (nonatomic, copy) NSString * _Nullable mediaAction;
@property (nonatomic) double mediaAssetDuration;
@property (nonatomic, copy) NSString * _Nullable mediaAssetIdentifier;
@property (nonatomic, copy) NSString * _Nullable mediaAssetTitle;
@property (nonatomic, copy) NSString * _Nullable mediaDelivery;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable metaData;
@property (nonatomic) double playHeadPosition;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable tags;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic, copy) NSString * _Nullable timezoneId;
@property (nonatomic, copy) NSString * _Nullable geotile;
@end


SWIFT_CLASS_NAMED("MultiClusterMO")
@interface MultiClusterMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class PointLocationMO;
@class NSSet;

@interface MultiClusterMO (SWIFT_EXTENSION(SerendipityLO))
- (void)addPointsObject:(PointLocationMO * _Nonnull)value;
- (void)removePointsObject:(PointLocationMO * _Nonnull)value;
- (void)addPoints:(NSSet * _Nonnull)values;
- (void)removePoints:(NSSet * _Nonnull)values;
@end


@interface MultiClusterMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) double clusterRadius;
@property (nonatomic, copy) NSString * _Nullable clusterType;
@property (nonatomic) BOOL hasResidenceTag;
@property (nonatomic) BOOL hasSemanticTag;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) BOOL ishighFideltyVisitedPlace;
@property (nonatomic) BOOL isHomeResidence;
@property (nonatomic) BOOL isMainCluster;
@property (nonatomic) BOOL isResidence;
@property (nonatomic) BOOL isWorkCluster;
@property (nonatomic, copy) NSString * _Nullable postalCode;
@property (nonatomic, copy) NSArray<NSDate *> * _Nullable residenceOnDates;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable semanticTags;
@property (nonatomic) double stDev;
@property (nonatomic, copy) NSString * _Nullable tileId;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable seiCodes;
@property (nonatomic, copy) NSString * _Nullable livesIn;
@property (nonatomic, strong) PointLocationMO * _Nullable centerPoint;
@property (nonatomic, strong) PointLocationMO * _Nullable outerPoint;
@property (nonatomic, strong) NSSet * _Nullable points;
@end


SWIFT_CLASS_NAMED("NoiseClusterMO")
@interface NoiseClusterMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface NoiseClusterMO (SWIFT_EXTENSION(SerendipityLO))
- (void)addNoisePointsObject:(PointLocationMO * _Nonnull)value;
- (void)removeNoisePointsObject:(PointLocationMO * _Nonnull)value;
- (void)addNoisePoints:(NSSet * _Nonnull)values;
- (void)removeNoisePoints:(NSSet * _Nonnull)values;
@end


@interface NoiseClusterMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable clusterType;
@property (nonatomic, strong) NSSet * _Nullable noisePoints;
@end


SWIFT_CLASS_NAMED("NotificationActionMO")
@interface NotificationActionMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class NotificationPayloadMO;
@class WoosActionMO;
@class ProfileActionMO;

@interface NotificationActionMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, strong) NotificationPayloadMO * _Nullable payload;
@property (nonatomic, strong) WoosActionMO * _Nullable wooAction;
@property (nonatomic, strong) CalendarActionMO * _Nullable calendarAction;
@property (nonatomic, strong) JourneyActionMO * _Nullable journeyAction;
@property (nonatomic, strong) ProfileActionMO * _Nullable profileAction;
@end


SWIFT_CLASS_NAMED("NotificationPayloadMO")
@interface NotificationPayloadMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface NotificationPayloadMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable resourceUrl;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable urlLink;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable promotion;
@property (nonatomic, strong) NotificationActionMO * _Nullable notificationAction;
@end


SWIFT_CLASS_NAMED("POIMO")
@interface POIMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface POIMO (SWIFT_EXTENSION(SerendipityLO))
- (void)addGeoPointsObject:(GeoPointsMO * _Nonnull)value;
- (void)removeGeoPointsObject:(GeoPointsMO * _Nonnull)value;
- (void)addGeoPoints:(NSSet * _Nonnull)values;
- (void)removeGeoPoints:(NSSet * _Nonnull)values;
@end


@interface POIMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable geoTileId;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timeZoneId;
@property (nonatomic, strong) NSSet * _Nullable geoPoints;
@end


SWIFT_CLASS_NAMED("PointLocationMO")
@interface PointLocationMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class XYCoordMO;

@interface PointLocationMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) double accuracy;
@property (nonatomic) int64_t count;
@property (nonatomic) double lat;
@property (nonatomic) double lng;
@property (nonatomic, copy) NSString * _Nullable mClusterReference;
@property (nonatomic, copy) NSString * _Nullable protoPointStatus;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable vanillaPointStatus;
@property (nonatomic, strong) MultiClusterMO * _Nullable centerPoint;
@property (nonatomic, strong) NoiseClusterMO * _Nullable noisePoints;
@property (nonatomic, strong) MultiClusterMO * _Nullable outerPoint;
@property (nonatomic, strong) MultiClusterMO * _Nullable points;
@property (nonatomic, strong) XYCoordMO * _Nullable xyPosition;
@end


SWIFT_CLASS_NAMED("ProfileActionMO")
@interface ProfileActionMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface ProfileActionMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable actionId;
@property (nonatomic, copy) NSString * _Nullable cvcqlVersion;
@property (nonatomic, copy) NSDate * _Nullable expires;
@property (nonatomic) int32_t minVersion;
@property (nonatomic, copy) NSString * _Nullable profileName;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic, strong) NotificationActionMO * _Nullable notificationAction;
@end


SWIFT_CLASS_NAMED("ProfileAudienceSegmentMO")
@interface ProfileAudienceSegmentMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface ProfileAudienceSegmentMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable profileName;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable query;
@property (nonatomic) BOOL isExternal;
@property (nonatomic) int32_t version;
@property (nonatomic, copy) NSString * _Nullable cvcqlVersion;
@property (nonatomic) int32_t updateEvery;
@property (nonatomic) int32_t identificationState;
@property (nonatomic, copy) NSString * _Nullable profileId;
@property (nonatomic, copy) NSDate * _Nullable expiryDate;
@property (nonatomic, copy) NSDate * _Nullable lastEvaluatedTime;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable annotations;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable annotationsPOIDependencies;
@end


SWIFT_CLASS_NAMED("ProfileErrorsMO")
@interface ProfileErrorsMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface ProfileErrorsMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable actionId;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic) int32_t errorCode;
@end


SWIFT_CLASS_NAMED("RangeActionMO")
@interface RangeActionMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface RangeActionMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) int32_t start;
@property (nonatomic) int32_t end;
@property (nonatomic, strong) WoosActionMO * _Nullable wooAction;
@end


SWIFT_CLASS_NAMED("RequestManagerMO")
@interface RequestManagerMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface RequestManagerMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable additionalInfo;
@property (nonatomic, copy) NSDate * _Nullable completeTime;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSDate * _Nullable previousLastSent;
@property (nonatomic, copy) NSDate * _Nullable requestInitalisedTime;
@property (nonatomic) BOOL success;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
@property (nonatomic, copy) NSString * _Nullable timeZoneId;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable urlEndpoint;
@end


SWIFT_CLASS_NAMED("SeiCodeMO")
@interface SeiCodeMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface SeiCodeMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) int32_t acorncode;
@property (nonatomic, copy) NSString * _Nullable postcode;
@property (nonatomic, copy) NSString * _Nullable tileId;
@property (nonatomic, copy) NSString * _Nullable nuts3;
@end


SWIFT_CLASS_NAMED("SemanticPOISMO")
@interface SemanticPOISMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface SemanticPOISMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) double lat;
@property (nonatomic) double lng;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable setId;
@property (nonatomic, copy) NSString * _Nullable tileId;
@property (nonatomic, copy) NSString * _Nullable pointId;
@end


SWIFT_CLASS_NAMED("SetIDStoreMO")
@interface SetIDStoreMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface SetIDStoreMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSArray<NSString *> * _Nullable clusterTypes;
@property (nonatomic) BOOL hasData;
@property (nonatomic) BOOL isStaleData;
@property (nonatomic, copy) NSDate * _Nullable lastRequestRecievedTimestamp;
@property (nonatomic, copy) NSString * _Nullable setName;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable tileIds;
@property (nonatomic) BOOL periodicPassBySet;
@end


SWIFT_CLASS_NAMED("SmartNotificationMO")
@interface SmartNotificationMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface SmartNotificationMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) BOOL clicked;
@property (nonatomic) BOOL created;
@property (nonatomic) BOOL displayed;
@property (nonatomic, copy) NSString * _Nullable errorDescription;
@property (nonatomic) int32_t errorType;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSDate * _Nullable receivedDate;
@property (nonatomic) BOOL resolved;
@property (nonatomic, copy) NSDate * _Nullable resolvedDate;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic) BOOL foreground;
@end


SWIFT_CLASS_NAMED("StateEventMO")
@interface StateEventMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface StateEventMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
@property (nonatomic) BOOL state;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic) BOOL shouldSend;
@end


SWIFT_CLASS_NAMED("StreamingHearbeatMO")
@interface StreamingHearbeatMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface StreamingHearbeatMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) BOOL isConcluded;
@property (nonatomic, copy) NSString * _Nullable mediaId;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic, copy) NSString * _Nullable mediaAssetTitle;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
@property (nonatomic) double mediaAssetDuration;
@property (nonatomic, copy) NSString * _Nullable mediaDelivery;
@property (nonatomic, copy) NSString * _Nullable timezoneId;
@end




SWIFT_CLASS_NAMED("WoosActionMO")
@interface WoosActionMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface WoosActionMO (SWIFT_EXTENSION(SerendipityLO))
- (void)addRangeActionObject:(RangeActionMO * _Nonnull)value;
- (void)removeRangeActionObject:(RangeActionMO * _Nonnull)value;
- (void)addRangeAction:(NSSet * _Nonnull)values;
- (void)removeRangeAction:(NSSet * _Nonnull)values;
@end


@interface WoosActionMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) int32_t index;
@property (nonatomic) int32_t offset;
@property (nonatomic, copy) NSString * _Nullable wooCommenceFrom;
@property (nonatomic, copy) NSDate * _Nullable displayDate;
@property (nonatomic, strong) NSSet * _Nullable rangeAction;
@property (nonatomic, strong) NotificationActionMO * _Nullable notificationAction;
@end


SWIFT_CLASS_NAMED("XYCoordMO")
@interface XYCoordMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface XYCoordMO (SWIFT_EXTENSION(SerendipityLO))
@property (nonatomic) double x;
@property (nonatomic) double y;
@property (nonatomic, strong) PointLocationMO * _Nullable pointLocation;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
